/**
 * @see https://github.com/radix-ui/design-system/blob/master/stitches.config.ts
 */
import * as colors from '@radix-ui/colors';

export const lightColors = {
  ...colors.gray,
  ...colors.mauve,
  ...colors.slate,
  ...colors.sage,
  ...colors.olive,
  ...colors.sand,
  ...colors.tomato,
  ...colors.red,
  ...colors.crimson,
  ...colors.pink,
  ...colors.plum,
  ...colors.purple,
  ...colors.violet,
  ...colors.indigo,
  ...colors.blue,
  ...colors.sky,
  ...colors.mint,
  ...colors.cyan,
  ...colors.teal,
  ...colors.green,
  ...colors.grass,
  ...colors.lime,
  ...colors.yellow,
  ...colors.amber,
  ...colors.orange,
  ...colors.brown,
  ...colors.bronze,
  ...colors.gold,

  ...colors.grayA,
  ...colors.mauveA,
  ...colors.slateA,
  ...colors.sageA,
  ...colors.oliveA,
  ...colors.sandA,
  ...colors.tomatoA,
  ...colors.redA,
  ...colors.crimsonA,
  ...colors.pinkA,
  ...colors.plumA,
  ...colors.purpleA,
  ...colors.violetA,
  ...colors.indigoA,
  ...colors.blueA,
  ...colors.skyA,
  ...colors.mintA,
  ...colors.cyanA,
  ...colors.tealA,
  ...colors.greenA,
  ...colors.grassA,
  ...colors.limeA,
  ...colors.yellowA,
  ...colors.amberA,
  ...colors.orangeA,
  ...colors.brownA,
  ...colors.bronzeA,
  ...colors.goldA,

  ...colors.whiteA,
  ...colors.blackA,

  // Semantic colors
  black: '#000',
  white: '#fff',
  hiContrast: '$mauve12',
  loContrast: 'white',
};

export const darkColors = {
  ...colors.grayDark,
  ...colors.mauveDark,
  ...colors.slateDark,
  ...colors.sageDark,
  ...colors.oliveDark,
  ...colors.sandDark,
  ...colors.tomatoDark,
  ...colors.redDark,
  ...colors.crimsonDark,
  ...colors.pinkDark,
  ...colors.plumDark,
  ...colors.purpleDark,
  ...colors.violetDark,
  ...colors.indigoDark,
  ...colors.blueDark,
  ...colors.skyDark,
  ...colors.mintDark,
  ...colors.cyanDark,
  ...colors.tealDark,
  ...colors.greenDark,
  ...colors.grassDark,
  ...colors.limeDark,
  ...colors.yellowDark,
  ...colors.amberDark,
  ...colors.orangeDark,
  ...colors.brownDark,
  ...colors.bronzeDark,
  ...colors.goldDark,

  ...colors.grayDarkA,
  ...colors.mauveDarkA,
  ...colors.slateDarkA,
  ...colors.sageDarkA,
  ...colors.oliveDarkA,
  ...colors.sandDarkA,
  ...colors.tomatoDarkA,
  ...colors.redDarkA,
  ...colors.crimsonDarkA,
  ...colors.pinkDarkA,
  ...colors.plumDarkA,
  ...colors.purpleDarkA,
  ...colors.violetDarkA,
  ...colors.indigoDarkA,
  ...colors.blueDarkA,
  ...colors.skyDarkA,
  ...colors.mintDarkA,
  ...colors.cyanDarkA,
  ...colors.tealDarkA,
  ...colors.greenDarkA,
  ...colors.grassDarkA,
  ...colors.limeDarkA,
  ...colors.yellowDarkA,
  ...colors.amberDarkA,
  ...colors.orangeDarkA,
  ...colors.brownDarkA,
  ...colors.bronzeDarkA,
  ...colors.goldDarkA,

  // Semantic colors
  hiContrast: '$mauve12',
  loContrast: '$mauve2',
};
